// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/engineer-portfolio/CuriousEngineer.tsx": () => import("../components/mockups/engineer-portfolio/CuriousEngineer.tsx")
};
